env: "develop"
version: "0.0.1"
temp_code_path: ""
server:
  host: "0.0.0.0"
  port: "6666"
  mode: "DEBUG"
  domain: ""
db:
  dialect: "postgres"
  user: ""
  password: ""
  host: ""
  port: 5432
  database: ""
  flag: "sslmode=disable"
jwt:
  issuer: ""
  access_token_exp_sec: 1400
  refresh_token_exp: 259200
  secret: 
redis:
  host: ""
  port: 6379
  database: 0
  auth: ""
  max_idle: 80
  max_active: 100
  idle_timeout: 2500
  notify_active: 1296000 # 15 days
  polling_active: 2592000 # 30 day
oauth:
  google:
    redirect_url: ""
    client_id:
    client_secret:
  facebook:
    redirect_url: ""
    client_id:
    client_secret:
  github:
    redirect_url: ""
    client_id:
    client_secret:
